name: Defender CLI Scan

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  defender-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ vars.REGISTRY_HOST }}/${{ vars.ARTIFACT_NAME }}:latest
        load: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Download Defender CLI
      run: |
        echo "Downloading Defender CLI" 
        curl -L -o defender "https://dfddefendercli-afdendpoint-dogfood-ahgnapadd4eecdbr.z01.azurefd.net/public/latest/Defender_linux-x64"
        chmod +x defender
        
    - name: Run Defender CLI Scan
      run: |
        echo "Running Defender CLI scan..."

        # Set temporary env vars
        DFD_BACKEND_ENVIRONMENT=PPE
        GDN_NUGET_SOURCE_FEED_OVERRIDE="https://pkgs.dev.azure.com/msdoustest/msdo/_packaging/msdotestfeed2/nuget/v3/index.json"
        
        # Set the CLI executable name

        CLI_EXECUTABLE="./defender"
        
        echo "Defender CLI executable: $CLI_EXECUTABLE"
        
        # Test if CLI runs (basic help/version check)
        echo "Testing CLI accessibility..."
        echo "Defender CLI Help"
        $CLI_EXECUTABLE --version

        # Run the actual scan command
        echo "Running Defender scan command..."
        echo "Command: $CLI_EXECUTABLE scan image ${{ vars.ARTIFACT_NAME }}:latest"
        
        # Execute the scan command (may fail without proper authentication)
        $CLI_EXECUTABLE scan image ${{ vars.ARTIFACT_NAME }}:latest || {
          echo "❌ Scan command failed - this may be due to:"
          echo "1. Missing authentication credentials"
          echo "2. Network connectivity issues" 
          echo "3. CLI configuration requirements"
          echo "4. Image not accessible to Defender CLI"
          exit 0  # Don't fail the workflow, just report the issue
        }
        
    - name: Upload Defender CLI results (placeholder)
      if: always()
      run: |
        echo "Placeholder for uploading Defender CLI scan results"
        echo "Results would be uploaded as artifacts here once scan is properly configured"
